apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders-ms-prod
  name: orders-ms-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-ms-prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders-ms-prod
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/microservices-nestjs-453917/nestmicroservicesdevtalles/orders-ms-prod
        name: orders-ms-prod
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: orders-ms-prod-secrets
              key: database_url
        resources: {}
status: {}
